<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vadimsva/waitMe/waitMe.min.css"/>
<script src="https://cdn.jsdelivr.net/gh/vadimsva/waitMe/waitMe.min.js"></script>

<h2>Variazioni automatiche</h2>
<form id="import_form_product_upload" method="post" enctype="multipart/form-data">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>

    <label>
        Import
        <input type="file" name="file">
    </label>

    <input type="submit" value="Carica file">
</form>
<p></p>

<form id="import_form_product_import" method="post" style="display: none;">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>
    <input id="import_form_product_import_file" name="file" type="hidden" value=""/>

    <p>
        Numero di righe: <span id="import_form_product_import_rows_count">Seleziona file...</span>
    </p>

    <button type="submit">Importa</button>
</form>
<p></p>

<table id="import_table_product_errors" style="display: none;"
       data-template-row="<tr><td>{row}</td></tr>">
    <thead>
    <tr>
        <th>Errori</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
</table>

<style>

    table {
        border-collapse: collapse;
    }

    table, th, td {
        border: 1px solid black;
    }

    #import_table_product_errors {
        width: 100%;
        max-height: 400px;
        border: none;
        display: block;
        overflow: scroll;
        border-collapse: collapse;
    }

    #import_table_product_errors th,
    #import_table_product_errors td {
        border: 1px solid grey;
        padding: 5px;
    }
</style>

<script>

    $j = jQuery.noConflict();

    $j(function () {

        $j("#import_form_product_upload").on("submit", function (e) {

            var form = $j(this);

            var formData = new FormData(this);

            loading('Caricamento file');
            $j.ajax({
                url: '<?php echo Mage::helper("adminhtml")->getUrl("thespaceimportexport/import/ajaximportparse"); ?>',
                method: 'post',
                data: formData,
                processData: false,
                cache: false,
                contentType: false,
                success: function (response) {
                    $j("#import_form_product_import").fadeIn(0);
                    $j("#import_form_product_import_file").val(response.file);
                    $j("#import_form_product_import_rows_count").html(response.rows_count);
                    console.log(response);
                    endLoading();
                },
                error: function (response) {
                    console.log(response);
                    endLoading();
                }
            });

            e.preventDefault();
        });

        $j("#import_form_product_import").on("submit", function (e) {

            var formData = new FormData(this);

            loading('Inserimento prodotti');
            $j.ajax({
                url: '<?php echo Mage::helper("adminhtml")->getUrl("thespaceimportexport/configurable/ajaximportrun"); ?>',
                method: 'post',
                data: formData,
                processData: false,
                cache: false,
                contentType: false,
                success: function (response) {
                    console.log(response);
                    $j.each(response.errors, function (index, error) {
                        printError(JSON.stringify(error));
                    });
                    endLoading();
                },
                error: function (response) {
                    console.log(response);
                    endLoading();
                }
            });

            e.preventDefault();
        });

        function loading(text) {
            $j("body").waitMe({
                bg: 'rgba(0, 0, 0, 0.6)',
                text: text,
                color: '#ecf0f1'
            });
        }

        function endLoading() {
            $j("body").waitMe('hide');
        }

        function printError(errorText) {
            var errorsTable = $j("#import_table_product_errors");
            errorsTable.fadeIn(0);

            var row = errorsTable.data('template-row');
            row = row.replace(/{row}/g, errorText);
            errorsTable.find("tbody").prepend(row);
        }
    });
</script>
