<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vadimsva/waitMe/waitMe.min.css"/>
<script src="https://cdn.jsdelivr.net/gh/vadimsva/waitMe/waitMe.min.js"></script>

<div id="import_products"
     data-url-cron-list="<?php echo Mage::helper("adminhtml")->getUrl("thespaceimportexport/cron/ajaximportlist"); ?>?isAjax=true&form_key=<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
     data-url-cron-add="<?php echo Mage::helper("adminhtml")->getUrl("thespaceimportexport/cron/ajaximportadd"); ?>?isAjax=true&form_key=<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
     data-url-cron-remove="<?php echo Mage::helper("adminhtml")->getUrl("thespaceimportexport/cron/ajaximportremove"); ?>?isAjax=true&form_key=<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
     data-form-key="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
>
    <h2>Caricamento prodotti a cron</h2>
    <form id="import_form_product_upload" method="post" enctype="multipart/form-data">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>

        <label>
            <select name="year">
                <?php foreach (range(date('Y'), intval(date('Y')) + 10) as $year) : ?>
                    <option value="<?php echo $year; ?>"><?php echo $year; ?></option>
                <?php endforeach; ?>
            </select>
        </label>
        <label>
            <select name="month">
                <?php foreach (range(1, 12) as $month) : ?>
                    <option <?php echo $month == intval(date('m')) ? 'selected="selected"' : ''; ?>
                            value="<?php echo $month; ?>"><?php echo $month; ?></option>
                <?php endforeach; ?>
            </select>
        </label>
        <label>
            <select name="day">
                <?php foreach (range(1, 31) as $day) : ?>
                    <option <?php echo $day == intval(date('d')) ? 'selected="selected"' : ''; ?>
                            value="<?php echo $day; ?>"><?php echo $day; ?></option>
                <?php endforeach; ?>
            </select>
        </label>
        <label>
            <select name="hour">
                <?php foreach (range(0, 23) as $hour) : ?>
                    <option <?php echo $hour == intval(date('H')) ? 'selected="selected"' : ''; ?>
                            value="<?php echo $hour; ?>"><?php echo $hour; ?></option>
                <?php endforeach; ?>
            </select>
        </label>
        <label>
            <select name="minute">
                <?php foreach (range(0, 59) as $minute) : ?>
                    <option <?php echo $minute == intval(date('i')) ? 'selected="selected"' : ''; ?>
                            value="<?php echo $minute; ?>"><?php echo $minute; ?></option>
                <?php endforeach; ?>
            </select>
        </label>
        <p></p>
        <label>
            Import
            <input type="file" name="file">
        </label>

        <input type="submit" value="Carica file">
    </form>
    <p></p>

    <table id="import_table_product_cron"
           data-template-row="<tr><td>{file}</td><td>{date}</td><td><button class='remove-button' data-file='{file}'>X</button></td></tr>">
        <thead>
        <tr>
            <th>File</th>
            <th>Esecuzione</th>
            <th>Azioni</th>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

<style>

    table {
        border-collapse: collapse;
    }

    table, th, td {
        border: 1px solid black;
    }

    #import_table_product_cron {
        width: 100%;
        max-height: 400px;
        border: none;
        display: block;
        overflow: scroll;
        border-collapse: collapse;
    }

    #import_table_product_cron th,
    #import_table_product_cron td {
        border: 1px solid grey;
        padding: 5px;
    }
</style>

<script>

    $j = jQuery.noConflict();

    $j(function () {

        var globals = $j("#import_products").data();
        var cronItemsTable = $j("#import_table_product_cron");

        updateCronList();

        $j("body").on("click", ".remove-button", function () {
            var t = $j(this);

            loading('Rimozione in corso');

            removeCronItem({
                file: t.data('file')
            })
                .done(function (response) {
                    updateCronList();
                    endLoading();
                });

        });

        $j("#import_form_product_upload").on("submit", function (e) {

            var formData = new FormData(this);

            loading('Caricamento file');

            addCronItem(formData)
                .done(function (response) {
                    endLoading();
                    updateCronList();
                });

            e.preventDefault();
        });

        function updateCronList() {
            getCronItems()
                .done(function (response) {
                    var files = response.files;
                    var html = "";
                    $j.each(files, function (key, fileItem) {
                        var row = cronItemsTable.data('template-row');
                        row = row.replace(/{file}/g, fileItem.name);
                        var dateString = "{year}/{month}/{day} {hour}:{minute}";
                        dateString = dateString.replace(/{year}/g, fileItem.date.Y);
                        dateString = dateString.replace(/{month}/g, fileItem.date.M);
                        dateString = dateString.replace(/{day}/g, fileItem.date.d);
                        dateString = dateString.replace(/{hour}/g, fileItem.date.H);
                        dateString = dateString.replace(/{minute}/g, fileItem.date.i);
                        row = row.replace(/{date}/g, dateString);
                        html += row;
                    });
                    cronItemsTable.find('tbody').html(html);
                });
        }

        function loading(text) {
            $j("body").waitMe({
                bg: 'rgba(0, 0, 0, 0.6)',
                text: text,
                color: '#ecf0f1'
            });
        }

        function endLoading() {
            $j("body").waitMe('hide');
        }

        function addCronItem(data) {
            return $j.ajax({
                url: globals.urlCronAdd,
                method: 'post',
                data: data,
                processData: false,
                cache: false,
                contentType: false,
            });
        }

        function getCronItems() {
            return $j.ajax({
                url: globals.urlCronList,
                method: 'get'
            });
        }

        function removeCronItem(data) {
            return $j.ajax({
                url: globals.urlCronRemove,
                method: 'post',
                data: data
            });
        }

    });
</script>
