<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vadimsva/waitMe/waitMe.min.css"/>
<script src="https://cdn.jsdelivr.net/gh/vadimsva/waitMe/waitMe.min.js"></script>

<div id="import_products"
     data-url-cron-list="<?php echo Mage::helper("adminhtml")->getUrl("thespaceimportexport/cron/ajaximportlist"); ?>?isAjax=true&form_key=<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
     data-url-cron-add="<?php echo Mage::helper("adminhtml")->getUrl("thespaceimportexport/cron/ajaximportadd"); ?>?isAjax=true&form_key=<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
     data-url-cron-remove="<?php echo Mage::helper("adminhtml")->getUrl("thespaceimportexport/cron/ajaximportremove"); ?>?isAjax=true&form_key=<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
     data-form-key="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
>
    <h2>Caricamento prodotti a cron</h2>
    <form id="import_form_product_upload" method="post" enctype="multipart/form-data">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>

        <label>
            Anno
            <select name="year">
                <?php foreach (range(date('Y'), intval(date('Y')) + 10) as $year) : ?>
                    <option value="<?php echo $year; ?>"><?php echo $year; ?></option>
                <?php endforeach; ?>
            </select>
        </label>
        <label>
            Mese
            <select name="month">
                <?php foreach (range(1, 12) as $month) : ?>
                    <option <?php echo $month == intval(date('m')) ? 'checked="checked"' : ''; ?>
                            value="<?php echo $month; ?>"><?php echo $month; ?></option>
                <?php endforeach; ?>
            </select>
        </label>
        <label>
            Giorno
            <select name="month">
                <?php foreach (range(1, 31) as $day) : ?>
                    <option <?php echo $day == intval(date('d')) ? 'checked="checked"' : ''; ?>
                            value="<?php echo $day; ?>"><?php echo $day; ?></option>
                <?php endforeach; ?>
            </select>
        </label>
        <label>
            Ora
            <select name="month">
                <?php foreach (range(1, 24) as $hour) : ?>
                    <option <?php echo $hour == intval(date('H')) ? 'checked="checked"' : ''; ?>
                            value="<?php echo $hour; ?>"><?php echo $hour; ?></option>
                <?php endforeach; ?>
            </select>
        </label>
        <label>
            Minuto
            <select name="month">
                <?php foreach (range(1, 60) as $minute) : ?>
                    <option <?php echo $minute == intval(date('i')) ? 'checked="checked"' : ''; ?>
                            value="<?php echo $minute; ?>"><?php echo $minute; ?></option>
                <?php endforeach; ?>
            </select>
        </label>

        <label>
            Import
            <input type="file" name="file">
        </label>

        <input type="submit" value="Carica file">
    </form>
    <p></p>

    <table id="import_table_product_cron"
           data-template-row="<tr><td>{file}</td><td>{time}</td></tr>">
        <thead>
        <tr>
            <th>File</th>
            <th>Esecuzione</th>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

<style>

    table {
        border-collapse: collapse;
    }

    table, th, td {
        border: 1px solid black;
    }

    #import_table_product_cron {
        width: 100%;
        max-height: 400px;
        border: none;
        display: block;
        overflow: scroll;
        border-collapse: collapse;
    }

    #import_table_product_cron th,
    #import_table_product_cron td {
        border: 1px solid grey;
        padding: 5px;
    }
</style>

<script>

    $j = jQuery.noConflict();

    $j(function () {

        var globals = $j("#import_products").data();
        var cronItemsTable = $j("#import_table_product_cron");

        getCronItems()
            .done(function (response) {
                var files = response.files;
                var html = "";
                $j.each(files, function (key, fileItem) {
                    var row = cronItemsTable.data('template-row');
                    row = row.replace(/{file}/g, fileItem.name);
                    row = row.replace(/{time}/g, JSON.stringify(fileItem.time));
                    html += row;
                });
                cronItemsTable.find('tbody').html(html);
            });

        $j("#import_form_product_upload").on("submit", function (e) {

            var formData = new FormData(this);

            loading('Caricamento file');

            addCronItem(formData)
                .done(function (response) {
                    alert('Si');
                });

            // parseImport(formData, {
            //     onComplete: function (response) {
            //
            //         endLoading();
            //
            //         // loading('Verifica del file');
            //         $j("#import_form_product_import_file").val(response.file);
            //         $j("#import_form_product_import_rows_count").html(response.rows_count);
            //         $j("#import_form_product_upload_info").fadeIn(0);
            //
            //         // checkImport({
            //         //     file: response.file
            //         // }, {
            //         //     onComplete: function (response) {
            //         //         endLoading();
            //
            //         if (response.status === 'OK') {
            //
            //             $j("#import_form_product_import").fadeIn(0);
            //         } else {
            //
            //             // Mostro errori file
            //
            //             $j.each(response.errors, function (index, error) {
            //                 printError(error);
            //             });
            //         }
            //         // },
            //         // onError: function (response) {
            //         //     alert(JSON.stringify(response));
            //         // }
            //         // });
            //     },
            //     onError: function (response) {
            //         alert(JSON.stringify(response));
            //     }
            // });

            e.preventDefault();
        });

        // var importProductsForm = $j("#import_form_product_import");
        //
        // importProductsForm.on("submit", function (e) {
        //
        //     var formData = new FormData(this);
        //     loading('');
        //
        //     splitImport(formData, {
        //         onComplete: function (response) {
        //             if (response.status === 'OK') {
        //                 var groupFiles = response.files;
        //
        //                 importGroups(groupFiles, 0, {
        //                     onProcess: function (response, index) {
        //
        //                         $j.each(response.errors, function (k, error) {
        //
        //                             var errorMessage = '<a href="{url}" target="_blank">{index}</a> {error}';
        //                             var url = globals.urlImportShowimportjson;
        //                             url = url.replace(/{file}/g, response.file);
        //
        //                             errorMessage = errorMessage.replace(/{url}/g, url);
        //                             errorMessage = errorMessage.replace(/{index}/g, index + 1);
        //                             errorMessage = errorMessage.replace(/{error}/g, JSON.stringify(error));
        //
        //
        //                             printError(errorMessage);
        //                         });
        //
        //                         var progress = 'Import in corso: {step} / {total}';
        //                         progress = progress.replace(/{step}/g, index + 1);
        //                         progress = progress.replace(/{total}/g, groupFiles.length);
        //                         // $j("#progress_status").html(progress);
        //                         loading(progress);
        //                     },
        //                     onComplete: function () {
        //                         console.log('Complete');
        //                         setTimeout(function () {
        //                             endLoading();
        //                         }, 500);
        //                     }
        //                 });
        //             }
        //         },
        //         onError: function (response) {
        //             alert(JSON.stringify(response));
        //         }
        //     });
        //
        //     e.preventDefault();
        // });

        function loading(text) {
            $j("body").waitMe({
                bg: 'rgba(0, 0, 0, 0.6)',
                text: text,
                color: '#ecf0f1'
            });
        }

        function endLoading() {
            $j("body").waitMe('hide');
        }

        function addCronItem(data) {
            return $j.ajax({
                url: globals.urlCronAdd,
                method: 'post',
                data: data,
                processData: false,
                cache: false,
                contentType: false,
            });
        }

        function getCronItems() {
            return $j.ajax({
                url: globals.urlCronList,
                method: 'get'
            });
        }

        // function parseImport(data, options) {
        //
        //     options = {
        //         ...{
        //             onComplete: function (response) {
        //
        //             },
        //             onError: function (response) {
        //
        //             }
        //         }, ...options
        //     };
        //
        //
        //     $j.ajax({
        //         url: globals.urlImportParse,
        //         method: 'post',
        //         data: data,
        //         processData: false,
        //         cache: false,
        //         contentType: false,
        //         success: function (response) {
        //             options.onComplete(response);
        //         },
        //         error: function (response) {
        //             options.onError(response);
        //         }
        //
        //     });
        // }

        // /**
        //  * Split files
        //  * @param data
        //  * @param options
        //  */
        // function splitImport(data, options) {
        //
        //     options = {
        //         ...{
        //             onComplete: function (response) {
        //
        //             },
        //             onError: function (response) {
        //
        //             }
        //         }, ...options
        //     };
        //
        //     $j.ajax({
        //         url: globals.urlImportSplit,
        //         method: 'post',
        //         data: data,
        //         processData: false,
        //         cache: false,
        //         contentType: false,
        //         success: function (response) {
        //             options.onComplete(response);
        //         },
        //         error: function (response) {
        //             options.onError(response);
        //         }
        //     });
        // }

        // /**
        //  * Split files
        //  * @param data
        //  * @param options
        //  */
        // function checkImport(data, options) {
        //
        //     options = {
        //         ...{
        //             onComplete: function (response) {
        //
        //             },
        //             onError: function (response) {
        //
        //             }
        //         }, ...options
        //     };
        //
        //     console.log(data);
        //
        //     $j.ajax({
        //         url: globals.urlImportCheck,
        //         method: 'post',
        //         data: data,
        //         success: function (response) {
        //             options.onComplete(response);
        //         },
        //         error: function (response) {
        //             options.onError(response);
        //         }
        //     });
        // }

        // function printError(errorText) {
        //     var errorsTable = $j("#import_table_product_errors");
        //     errorsTable.fadeIn(0);
        //
        //     var row = errorsTable.data('template-row');
        //     row = row.replace(/{row}/g, errorText);
        //     errorsTable.find("tbody").prepend(row);
        // }

        //$j("#import_form_product_import").on("submit", function (e) {
        //
        //    var formData = new FormData(this);
        //
        //    $j.ajax({
        //        url: '<?php //echo Mage::helper("adminhtml")->getUrl("thespaceimportexport/import/ajaximportcheck"); ?>//',
        //        method: 'post',
        //        data: formData,
        //        processData: false,
        //        cache: false,
        //        contentType: false,
        //        success: function (response) {
        //
        //            var errorTable = $j("#import_table_product_errors");
        //            errorTable.find("tbody").html('');
        //            errorTable.fadeIn(0);
        //
        //            if (response.errors.length) {
        //                var rowTemplate = errorTable.data('template-row');
        //                var rowsData = "";
        //
        //                for (var i = 0; i < response.errors.length; i++) {
        //                    var error = response.errors[i];
        //                    var rowItem = rowTemplate;
        //                    rowItem = rowItem.replace(/{row}/g, error.row);
        //                    rowItem = rowItem.replace(/{columns}/g, error.columns);
        //                    rowsData += rowItem;
        //                }
        //                errorTable.find("tbody").html(rowsData);
        //            } else {
        //
        //                $j.ajax({
        //                    url: '<?php //echo Mage::helper("adminhtml")->getUrl("thespaceimportexport/import/ajaximportrun"); ?>//',
        //                    method: 'post',
        //                    data: formData,
        //                    processData: false,
        //                    cache: false,
        //                    contentType: false,
        //                    success: function (response) {
        //                        console.log(response);
        //                    },
        //                    error: function (response) {
        //
        //                    }
        //                });
        //            }
        //        },
        //        error: function (response) {
        //
        //        }
        //    });
        //
        //    e.preventDefault();
        //});
    });
</script>
