<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vadimsva/waitMe/waitMe.min.css"/>
<script src="https://cdn.jsdelivr.net/gh/vadimsva/waitMe/waitMe.min.js"></script>

<h2>Caricamento prodotti</h2>
<form id="import_form_product_upload" method="post" enctype="multipart/form-data">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>

    <label>
        Import
        <input type="file" name="file">
    </label>

    <input type="submit" value="Seleziona file">
</form>
<p></p>

<form id="import_form_product_import" method="post" style="display: none;">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>
    <input id="import_form_product_import_file" name="file" type="hidden" value=""/>

    <p>
        Numero di righe: <span id="import_form_product_import_rows_count">Seleziona file...</span>
    </p>

    <input type="submit" value="Seleziona file">
</form>
<p></p>

<script>

    $j = jQuery.noConflict();

    $j(function () {

        $j("#import_form_product_upload").on("submit", function (e) {

            var formData = new FormData(this);

            $j.ajax({
                url: '<?php echo Mage::helper("adminhtml")->getUrl("thespaceimportexport/import/ajaximportparse"); ?>',
                method: 'post',
                data: formData,
                processData: false,
                cache: false,
                contentType: false,
                success: function (response) {
                    console.log(response);
                    $j("#import_form_product_import").fadeIn(0);
                },
                error: function (response) {

                }
            });

            e.preventDefault();
        });
    });
</script>
