<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vadimsva/waitMe/waitMe.min.css"/>
<script src="https://cdn.jsdelivr.net/gh/vadimsva/waitMe/waitMe.min.js"></script>

<h2>Upload immagini</h2>
<form id="upload_images" method="post" enctype="multipart/form-data">

</form>
<p></p>
<p></p>
<br>

<script>
    $j = jQuery.noConflict();

    $j(function () {

    
    });

</script>
