<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vadimsva/waitMe/waitMe.min.css"/>
<script src="https://cdn.jsdelivr.net/gh/vadimsva/waitMe/waitMe.min.js"></script>

<form id="export_form" method="post"
      action="<?php echo Mage::helper("adminhtml")->getUrl("csvimportexport/export/export"); ?>">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>

    <div>
        <label>
            Marca
            <select id="select_manufacturer" name="manufacturer">
                <option value>-</option>
                <?php
                $attribute = Mage::getSingleton('eav/config')
                    ->getAttribute(Mage_Catalog_Model_Product::ENTITY, 'manufacturer');
                
                if ($attribute->usesSource()) {
                    $options = $attribute->getSource()->getAllOptions(false);
                    foreach ($options as $option) : ?>
                        <option value="<?php echo $option['value']; ?>"><?php echo $option['label']; ?></option>
                    <?php endforeach;
                }
                ?>
            </select>
        </label>
        <p></p>
        <?php
        $stores = Mage::app()->getStores();
        
        foreach ($stores as $store) : ?>
            <label>Store view "<?php echo $store->getName(); ?>" <input type="checkbox"
                                                                        name="store_view_<?php echo $store->getCode(); ?>"></label>
            <p></p>
        <?php endforeach; ?>
        &nbsp;
        <label>
            Pagina
            <select id="select_page" data-template="<option value='{page}'>{page}</option>" name="page"></select>
        </label>
        <p></p>
        <input type="submit" value="Esporta">
    </div>

    <br>

    <div>
        <h2>Immagini</h2>
        <label>
            Includi Immagini
            <input type="checkbox" name="images" value="1"/>
        </label>
    </div>

    <br>

    <div>
        <h2>Attributi</h2>
        <?php
        $attributes = Mage::getSingleton('eav/config')
            ->getEntityType(Mage_Catalog_Model_Product::ENTITY)
            ->getAttributeCollection()
            ->addSetInfo();
        
        /** @var Mage_Catalog_Model_Resource_Eav_Attribute $attribute */
        foreach ($attributes as $attribute) : ?>
            <div class="attribute">
                <label><?php echo empty($attribute->getFrontendLabel()) ? ucfirst($attribute->getName()) : $attribute->getFrontendLabel(); ?>
                    <input type="checkbox" name="att_<?php echo $attribute->getName(); ?>" value="1"</label> &nbsp;
            </div>
        <?php endforeach; ?>
    </div>

</form>

<style>
    .attribute {
        width: 100%;
        max-width: 250px;
        display: inline-block;
    }
</style>

<script>

    $j = jQuery.noConflict();

    function refreshPages() {
        var $select = jQuery("#select_page");
        jQuery("body").waitMe({
            effect: 'pulse',
            text: 'Aggiornamento pagine...',
            bg: 'rgba(51,51,51,0.8)',
            color: '#ffffff'
        });
        var $form = $j("#export_form");
        var formData = new FormData($form[0]);
        $j.ajax({
            url: "<?php echo Mage::helper("adminhtml")->getUrl("csvimportexport/export/pages"); ?>",
            type: 'POST',
            data: formData,
            success: function (response) {
                $select.empty();
                var $countPages = response.result;
                for (var $i = 1; $i <= $countPages; $i++) {
                    var $item = $select.data("template");
                    $item = $item.replace(/{page}/g, $i);
                    $select.append($item);
                }
                jQuery("body").waitMe("hide");
            },
            error: function (request, status, error) {
                jQuery("body").waitMe("hide");
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }

    $j(function () {

        $j("#select_manufacturer").on("change", function () {
            refreshPages();
        });
    });
</script>