<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vadimsva/waitMe/waitMe.min.css"/>
<script src="https://cdn.jsdelivr.net/gh/vadimsva/waitMe/waitMe.min.js"></script>

<h2>Export categorie</h2>
<form id="export_categories_form" method="post"
      action="<?php echo Mage::helper("adminhtml")->getUrl("thespaceimportexport/exportcategories/export"); ?>">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>

    <button type="submit">Esporta</button>
</form>