<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vadimsva/waitMe/waitMe.min.css"/>
<script src="https://cdn.jsdelivr.net/gh/vadimsva/waitMe/waitMe.min.js"></script>

<h2>Configurazione</h2>
<form id="configuration_form" method="post" enctype="multipart/form-data">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>

    <h4>Defaults</h4>
    
    <?php $configurationHelper = Mage::helper('thespaceimportexport/Configuration'); ?>
    <?php foreach (Thespace_ImportExport_Helper_Configuration::DEFAULT_CONFIGURATION_OPTIONS as $default) : ?>

        <p>
            <label>
                <?php
                $tmp = explode("/", $default);
                $label = ucwords(str_replace("_", " ", array_pop($tmp)))
                ?>
                <span><?php echo $label; ?></span>
                <input type="text" name="<?php echo $default; ?>"
                       value="<?php echo $configurationHelper->get($default); ?>">
            </label>
        </p>
    
    <?php endforeach; ?>

    <button type="submit">Salva</button>
</form>

<script>

    $j = jQuery.noConflict();

    $j(function () {


        var form = $j("#configuration_form");
        form.on("submit", function (e) {
            var data = $j(this).serialize();
            saveData(data)
                .done(function (response) {
                    alert('Salvato');
                });

            e.preventDefault();
        });

        function saveData(data) {
            return $j.ajax({
                url: '<?php echo Mage::helper("adminhtml")->getUrl("thespaceimportexport/configuration/update"); ?>?isAjax=true',
                data: data,
                method: 'get'
            });
        }
    });

</script>