<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vadimsva/waitMe/waitMe.min.css"/>
<script src="https://cdn.jsdelivr.net/gh/vadimsva/waitMe/waitMe.min.js"></script>

<h2>Configurazione</h2>
<form id="import_form_product_upload" method="post" enctype="multipart/form-data">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>

    <h4>Defaults</h4>
    
    <?php $configurationHelper = Mage::helper('thespaceimportexport/Configuration'); ?>
    <?php foreach (Thespace_ImportExport_Helper_Configuration::DEFAULT_CONFIGURATION_OPTIONS as $default) : ?>

        <p>
            <label>
                <span><?php echo ucwords(str_replace("_", " ", $default)); ?></span>
                <input type="text" name="<?php echo $default; ?>"
                       value="<?php echo $configurationHelper->get($default); ?>">
            </label>
        </p>
    
    <?php endforeach; ?>

</form>

